# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://CMHA-Hack-A-Thon.github.io"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
social:
  twitter_handle: "MLHacks"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "Example Hacks | 5/6 August 2016"
  description: "This is a sample hackathon website that you can use by following instructions on GitHub."
  image:       "https://prime.mlh.io/img/logos/mlh-prime-color.svg"

# Event information.
event:
  name:        "Cleveland Housing Hackathon"
  description: "The hackathon will aim to aid the HCVP, Housing Choice Voucher Program, in its goal of finding well-resourced to increase mobility"
  date:        "8 April 2017"
  location:    "Cleveland, OH, United States"

  trust_badge:
    year:   "2017"  # season year
    region: "na"    # "na" or "eu"
    color:  "black" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    links:
      - text: "Register"
        href: "#"
      - text: "Sponsor"
        href: "#"

  about:
    description: >
      CMHA and DigitalC and Cleveland State University are partnering to host the Cleveland Housing Hackathon. The hackathon will aim aid the HCVP,
      Housing Choice Voucher Program, in its goal of finding well-resourced to increase mobility.
      Employment, retail, education, transportation and healthcare are among the factors to be considered when employing solutions.
       The hackathon will hope to produce either an app,
       visualization or product to aid the HCVP using data based on four interlocking tracks: transportation, wellness, education and connectivity.

  # Info Sections
  info:
    sections:
      - image: "images/cmhalogo.jpg"
        title:
        description: >

      - image: "images/CSUlogo.png"
        title:
        description: >

      - image: "images/download.png"
        title:
        description: >




  # Frequently asked questions.
  faq:
    - question: "What is a hackathon?"
      answer: >
        A Hackathon is a social event that combines talent, expertise, data, and out-of-the-box thinking
        to solve local challenges. It's an invention marathon. People come together to build cool
        software & hardware hacks over 24-48 hours. It's
        [very beginner friendly](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl).
    - question: "How much does it cost?"
      answer: >
        Nothing. Attending a hackathon is free.
    - question: "Do I need to be a student to attend?"
      answer: >
        Nope. Everyone wanting to chip in can come and help!
    - question: "Where is the event?"
      answer: >
        The event is being hosted at CSU.
    - question: "What is Major League Hacking?"
      answer: >
        Major League Hacking is [the official student hackathon league](https://mlh.io) in North America & Europe.
        We work with over 200 Member Events and empower over 70,000 students every year.
    - question: "Is there a code of conduct?"
      answer: >
        Yes there is. We enforce it very strongly. You can [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).

  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
